[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

[[redirects]]
  from = "/tesekkurler"
  to = "/tesekkurler.html"
  status = 200
